#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/setup'
require 'dotenv'
Dotenv.load
require 'truck'
require 'transactions'
require 'events'

txs = Transactions.new
txs.load
txs.build_set

evs = Events.new
evs.load
evs.build_set

unmatched_ts = txs.set - evs.set

CSV.open('out.csv', 'w') do |csv|
  unmatched_ts.each do |id|
    csv << [id]
  end
end
